import { useEffect, useState } from 'react'
import { Pencil, Trash2 } from 'lucide-react'
import { api, apiMessage } from '../api/client'
import { Button, EmptyState, Field, LoadingState, Modal, Notice, PageHeader } from '../components/UI'

export default function CategoriesPage() {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [modal, setModal] = useState(null); const [form, setForm] = useState({ name: '', description: '' }); const [saving, setSaving] = useState(false)
  async function load() { try { setLoading(true); setItems((await api.get('/categories/')).data) } catch (e) { setError(apiMessage(e)) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  function open(item) { setForm(item ? { name: item.name, description: item.description || '', category_id: item.category_id } : { name: '', description: '' }); setModal(item ? 'edit' : 'new') }
  async function submit(e) { e.preventDefault(); setSaving(true); try { if (modal === 'edit') await api.put(`/categories/${form.category_id}`, { name: form.name, description: form.description || null }); else await api.post('/categories/', { name: form.name, description: form.description || null }); setModal(null); setNotice('Category saved.'); load() } catch (e) { setError(apiMessage(e)) } finally { setSaving(false) } }
  async function remove(item) { if (!window.confirm(`Delete ${item.name}?`)) return; try { await api.delete(`/categories/${item.category_id}`); load() } catch (e) { setError(apiMessage(e)) } }
  return <><PageHeader title="Categories" description="Organise your product catalogue." action={<Button onClick={() => open()}>Add category</Button>} />{notice && <Notice type="success">{notice}</Notice>}{error && <Notice>{error}</Notice>}{loading ? <LoadingState /> : items.length === 0 ? <EmptyState title="No categories yet" /> : <div className="card-grid">{items.map((item) => <div className="info-card" key={item.category_id}><div className="info-card-top"><div className="category-icon">{item.name.slice(0, 1).toUpperCase()}</div><div className="actions"><button onClick={() => open(item)} aria-label="Edit category"><Pencil size={16} /></button><button onClick={() => remove(item)} aria-label="Delete category"><Trash2 size={16} /></button></div></div><h3>{item.name}</h3><p>{item.description || 'No description added.'}</p></div>)}</div>}{modal && <Modal title={modal === 'edit' ? 'Edit category' : 'Add category'} onClose={() => setModal(null)}><form className="modal-form" onSubmit={submit}><Field label="Name"><input required maxLength="100" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="e.g. Homeware" /></Field><Field label="Description"><textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Optional description" rows="3" /></Field><div className="modal-actions"><Button variant="secondary" onClick={() => setModal(null)}>Cancel</Button><Button type="submit" loading={saving}>Save category</Button></div></form></Modal>}</>
}
