import { useEffect, useState } from 'react'
import { Pencil, Trash2 } from 'lucide-react'
import { api, apiMessage } from '../api/client'
import { useAuth } from '../auth/AuthContext'
import { Button, EmptyState, Field, LoadingState, Modal, Notice, PageHeader, SearchBox } from '../components/UI'

const empty = { first_name: '', last_name: '', email: '', phone: '' }
export default function CustomersPage() {
  const { user } = useAuth(); const canDelete = ['admin', 'manager'].includes(user?.role)
  const [items, setItems] = useState([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [modal, setModal] = useState(null); const [form, setForm] = useState(empty); const [saving, setSaving] = useState(false)
  async function load() { try { setLoading(true); setItems((await api.get('/customers/')).data) } catch (e) { setError(apiMessage(e)) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const filtered = items.filter((i) => `${i.first_name} ${i.last_name} ${i.email || ''}`.toLowerCase().includes(search.toLowerCase()))
  function open(item) { setForm(item ? { ...item } : empty); setModal(item ? 'edit' : 'new'); setError('') }
  async function submit(e) { e.preventDefault(); setSaving(true); setError(''); try { const payload = { ...form, email: form.email || null, phone: form.phone || null }; if (modal === 'edit') await api.put(`/customers/${form.customer_id}`, payload); else await api.post('/customers/', payload); setModal(null); load() } catch (e) { setError(apiMessage(e)) } finally { setSaving(false) } }
  async function remove(item) { if (!window.confirm(`Delete ${item.first_name} ${item.last_name}?`)) return; try { await api.delete(`/customers/${item.customer_id}`); load() } catch (e) { setError(apiMessage(e)) } }
  return <><PageHeader title="Customers" description="Your customer directory for every sale." action={<Button onClick={() => open()}>Add customer</Button>} /><div className="toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search customers..." /></div>{error && <Notice>{error}</Notice>}{loading ? <LoadingState /> : filtered.length === 0 ? <EmptyState title={search ? 'No customers found' : 'No customers yet'} /> : <div className="table-card"><table><thead><tr><th>Customer</th><th>Email</th><th>Phone</th><th>Added</th><th /></tr></thead><tbody>{filtered.map((item) => <tr key={item.customer_id}><td><div className="person-cell"><div className="mini-avatar">{item.first_name.slice(0, 1)}</div><strong>{item.first_name} {item.last_name}</strong></div></td><td>{item.email || '—'}</td><td>{item.phone || '—'}</td><td>{new Date(item.created_at).toLocaleDateString()}</td><td className="actions"><button onClick={() => open(item)} aria-label="Edit customer"><Pencil size={16} /></button>{canDelete && <button onClick={() => remove(item)} aria-label="Delete customer"><Trash2 size={16} /></button>}</td></tr>)}</tbody></table></div>}{modal && <Modal title={modal === 'edit' ? 'Edit customer' : 'Add customer'} onClose={() => setModal(null)}><form className="modal-form" onSubmit={submit}><Notice>{error}</Notice><div className="form-grid"><Field label="First name"><input required maxLength="50" value={form.first_name} onChange={(e) => setForm({ ...form, first_name: e.target.value })} /></Field><Field label="Last name"><input required maxLength="50" value={form.last_name} onChange={(e) => setForm({ ...form, last_name: e.target.value })} /></Field><Field label="Email"><input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></Field><Field label="Phone"><input maxLength="20" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></Field></div><div className="modal-actions"><Button variant="secondary" onClick={() => setModal(null)}>Cancel</Button><Button type="submit" loading={saving}>Save customer</Button></div></form></Modal>}</>
}
