import { useEffect, useMemo, useState } from 'react'
import { Pencil, Trash2 } from 'lucide-react'
import { api, apiMessage } from '../api/client'
import { useAuth } from '../auth/AuthContext'
import { Button, EmptyState, Field, LoadingState, Modal, Notice, PageHeader, SearchBox } from '../components/UI'

const blank = { name: '', sku: '', description: '', category_id: '', supplier_id: '', cost_price: '', selling_price: '', low_stock_threshold: '10' }
function ProductForm({ value, categories, suppliers, onChange, onSubmit, onClose, loading, error }) {
  const set = (key) => (e) => onChange({ ...value, [key]: e.target.value })
  return <form className="modal-form" onSubmit={onSubmit}><Notice>{error}</Notice><div className="form-grid"><Field label="Product name"><input required maxLength="150" value={value.name} onChange={set('name')} placeholder="e.g. Ceramic mug" /></Field><Field label="SKU"><input required maxLength="50" value={value.sku} onChange={set('sku')} placeholder="SKU-001" /></Field><Field label="Category"><select value={value.category_id} onChange={set('category_id')}><option value="">No category</option>{categories.map((item) => <option key={item.category_id} value={item.category_id}>{item.name}</option>)}</select></Field><Field label="Supplier"><select value={value.supplier_id} onChange={set('supplier_id')}><option value="">No supplier</option>{suppliers.map((item) => <option key={item.supplier_id} value={item.supplier_id}>{item.company_name}</option>)}</select></Field><Field label="Cost price"><input required min="0" step="0.01" type="number" value={value.cost_price} onChange={set('cost_price')} placeholder="0.00" /></Field><Field label="Selling price"><input required min="0" step="0.01" type="number" value={value.selling_price} onChange={set('selling_price')} placeholder="0.00" /></Field><Field label="Low stock threshold"><input required min="0" type="number" value={value.low_stock_threshold} onChange={set('low_stock_threshold')} /></Field><Field label="Description"><input value={value.description} onChange={set('description')} placeholder="Optional description" /></Field></div><div className="modal-actions"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" loading={loading}>Save product</Button></div></form>
}

export default function ProductsPage() {
  const { user } = useAuth(); const canManage = ['admin', 'manager'].includes(user?.role)
  const [products, setProducts] = useState([]); const [categories, setCategories] = useState([]); const [suppliers, setSuppliers] = useState([])
  const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  const [modal, setModal] = useState(null); const [form, setForm] = useState(blank); const [saving, setSaving] = useState(false); const [formError, setFormError] = useState('')
  async function load() { setLoading(true); setError(''); try { const [p, c, s] = await Promise.all([api.get('/products/', { params: search ? { search } : {} }), api.get('/categories/'), api.get('/suppliers/')]); setProducts(p.data); setCategories(c.data); setSuppliers(s.data) } catch (e) { setError(apiMessage(e)) } finally { setLoading(false) } }
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer) }, [search])
  function open(item = null) { setForm(item ? { ...item, category_id: item.category_id || '', supplier_id: item.supplier_id || '', description: item.description || '' } : blank); setFormError(''); setModal(item ? 'edit' : 'new') }
  async function submit(e) { e.preventDefault(); setSaving(true); setFormError(''); const payload = { ...form, category_id: form.category_id ? Number(form.category_id) : null, supplier_id: form.supplier_id ? Number(form.supplier_id) : null, cost_price: Number(form.cost_price), selling_price: Number(form.selling_price), low_stock_threshold: Number(form.low_stock_threshold) }; try { if (modal === 'edit') await api.put(`/products/${form.product_id}`, payload); else await api.post('/products/', payload); setModal(null); setNotice('Product saved successfully.'); load() } catch (e) { setFormError(apiMessage(e)) } finally { setSaving(false) } }
  async function remove(item) { if (!window.confirm(`Delete ${item.name}?`)) return; try { await api.delete(`/products/${item.product_id}`); setNotice('Product deleted.'); load() } catch (e) { setError(apiMessage(e)) } }
  const categoryName = useMemo(() => Object.fromEntries(categories.map((c) => [c.category_id, c.name])), [categories])
  return <><PageHeader title="Products" description={`${products.length} products in your catalogue.`} action={canManage && <Button onClick={() => open()}>Add product</Button>} /><div className="toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search name or SKU..." /></div>{notice && <Notice type="success" onClose={() => setNotice('')}>{notice}</Notice>}{error && <Notice onClose={() => setError('')}>{error}</Notice>}{loading ? <LoadingState /> : products.length === 0 ? <EmptyState title={search ? 'No products found' : 'No products yet'} message={search ? 'Try a different search.' : 'Add your first product to start tracking stock.'} /> : <div className="table-card"><table><thead><tr><th>Product</th><th>SKU</th><th>Category</th><th>Price</th><th>In stock</th>{canManage && <th />}</tr></thead><tbody>{products.map((item) => <tr key={item.product_id}><td><strong>{item.name}</strong><small className="muted">{item.description || '—'}</small></td><td><code>{item.sku}</code></td><td>{categoryName[item.category_id] || 'Uncategorised'}</td><td><strong>{formatCurrency(item.selling_price)}</strong><small className="muted">cost {formatCurrency(item.cost_price)}</small></td><td><span className={`stock-pill ${item.low_stock ? 'low' : 'ok'}`}>{item.stock_quantity} {item.low_stock && '· low'}</span></td>{canManage && <td className="actions"><button onClick={() => open(item)} aria-label="Edit product"><Pencil size={16} /></button><button onClick={() => remove(item)} aria-label="Delete product"><Trash2 size={16} /></button></td>}</tr>)}</tbody></table></div>}{modal && <Modal title={modal === 'edit' ? 'Edit product' : 'Add product'} onClose={() => setModal(null)}><ProductForm value={form} categories={categories} suppliers={suppliers} onChange={setForm} onSubmit={submit} onClose={() => setModal(null)} loading={saving} error={formError} /></Modal>}</>
}

function formatCurrency(value) { return new Intl.NumberFormat(undefined, { style: 'currency', currency: 'INR' }).format(Number(value || 0)) }
