import { useEffect, useState } from 'react'
import { Pencil, Trash2 } from 'lucide-react'
import { api, apiMessage } from '../api/client'
import { useAuth } from '../auth/AuthContext'
import { Button, EmptyState, Field, LoadingState, Modal, Notice, PageHeader, SearchBox } from '../components/UI'

const empty = { company_name: '', contact_name: '', email: '', phone: '', address: '' }
export default function SuppliersPage() {
  const { user } = useAuth(); const canManage = ['admin', 'manager'].includes(user?.role)
  const [items, setItems] = useState([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [modal, setModal] = useState(null); const [form, setForm] = useState(empty); const [saving, setSaving] = useState(false)
  async function load() { try { setLoading(true); setItems((await api.get('/suppliers/')).data) } catch (e) { setError(apiMessage(e)) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const filtered = items.filter((i) => `${i.company_name} ${i.contact_name || ''} ${i.email || ''}`.toLowerCase().includes(search.toLowerCase()))
  function open(item) { setForm(item ? { ...item } : empty); setModal(item ? 'edit' : 'new'); setError('') }
  async function submit(e) { e.preventDefault(); setSaving(true); setError(''); const payload = { ...form, email: form.email || null, contact_name: form.contact_name || null, phone: form.phone || null, address: form.address || null }; try { if (modal === 'edit') await api.put(`/suppliers/${form.supplier_id}`, payload); else await api.post('/suppliers/', payload); setModal(null); load() } catch (e) { setError(apiMessage(e)) } finally { setSaving(false) } }
  async function remove(item) { if (!window.confirm(`Delete ${item.company_name}?`)) return; try { await api.delete(`/suppliers/${item.supplier_id}`); load() } catch (e) { setError(apiMessage(e)) } }
  return <><PageHeader title="Suppliers" description="Keep your vendor relationships in one place." action={canManage && <Button onClick={() => open()}>Add supplier</Button>} /><div className="toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search suppliers..." /></div>{error && <Notice onClose={() => setError('')}>{error}</Notice>}{loading ? <LoadingState /> : filtered.length === 0 ? <EmptyState title={search ? 'No suppliers found' : 'No suppliers yet'} /> : <div className="table-card"><table><thead><tr><th>Company</th><th>Contact</th><th>Email</th><th>Phone</th><th>Address</th>{canManage && <th />}</tr></thead><tbody>{filtered.map((item) => <tr key={item.supplier_id}><td><strong>{item.company_name}</strong><small className="muted">Added {new Date(item.created_at).toLocaleDateString()}</small></td><td>{item.contact_name || '—'}</td><td>{item.email || '—'}</td><td>{item.phone || '—'}</td><td>{item.address || '—'}</td>{canManage && <td className="actions"><button onClick={() => open(item)} aria-label="Edit supplier"><Pencil size={16} /></button><button onClick={() => remove(item)} aria-label="Delete supplier"><Trash2 size={16} /></button></td>}</tr>)}</tbody></table></div>}{modal && <Modal title={modal === 'edit' ? 'Edit supplier' : 'Add supplier'} onClose={() => setModal(null)}><form className="modal-form" onSubmit={submit}><Notice>{error}</Notice><div className="form-grid"><Field label="Company name"><input required value={form.company_name} onChange={(e) => setForm({ ...form, company_name: e.target.value })} /></Field><Field label="Contact name"><input value={form.contact_name} onChange={(e) => setForm({ ...form, contact_name: e.target.value })} /></Field><Field label="Email"><input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></Field><Field label="Phone"><input maxLength="20" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></Field></div><Field label="Address"><textarea rows="2" value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} /></Field><div className="modal-actions"><Button variant="secondary" onClick={() => setModal(null)}>Cancel</Button><Button type="submit" loading={saving}>Save supplier</Button></div></form></Modal>}</>
}
