import { useEffect, useState } from 'react'
import { api, apiMessage } from '../api/client'
import { Button, EmptyState, Field, LoadingState, Modal, Notice, PageHeader, formatCurrency, formatDate } from '../components/UI'
import { useAuth } from '../auth/AuthContext'

function LineEditor({ lines, products, purchase, setLines }) {
  function update(index, key, value) { setLines(lines.map((line, i) => i === index ? { ...line, [key]: value } : line)) }
  return <div className="line-editor"><div className="line-head"><span>Product</span><span>Quantity</span>{purchase && <span>Unit cost</span>}<span /></div>{lines.map((line, index) => <div className="line-row" key={index}><select required value={line.product_id} onChange={(e) => update(index, 'product_id', e.target.value)}><option value="">Choose product</option>{products.map((p) => <option key={p.product_id} value={p.product_id}>{p.name} · {p.stock_quantity} in stock</option>)}</select><input required min="1" type="number" value={line.quantity} onChange={(e) => update(index, 'quantity', e.target.value)} />{purchase && <input min="0" step="0.01" type="number" value={line.unit_cost} onChange={(e) => update(index, 'unit_cost', e.target.value)} placeholder="Product cost" />}<button type="button" className="remove-line" onClick={() => setLines(lines.filter((_, i) => i !== index))} disabled={lines.length === 1}>×</button></div>)}<button className="add-line" type="button" onClick={() => setLines([...lines, purchase ? { product_id: '', quantity: '1', unit_cost: '' } : { product_id: '', quantity: '1' }])}>+ Add another line</button></div>
}

export function PurchasesPage() {
  const { user } = useAuth(); const canBuy = ['admin', 'manager'].includes(user?.role)
  const [items, setItems] = useState([]); const [suppliers, setSuppliers] = useState([]); const [products, setProducts] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [modal, setModal] = useState(false); const [supplier, setSupplier] = useState(''); const [lines, setLines] = useState([{ product_id: '', quantity: '1', unit_cost: '' }]); const [saving, setSaving] = useState(false)
  async function load() { try { setLoading(true); const [p, s, pr] = await Promise.all([api.get('/purchases/'), api.get('/suppliers/'), api.get('/products/')]); setItems(p.data); setSuppliers(s.data); setProducts(pr.data) } catch (e) { setError(apiMessage(e)) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  async function submit(e) { e.preventDefault(); setSaving(true); setError(''); try { await api.post('/purchases/', { supplier_id: Number(supplier), items: lines.map((line) => ({ product_id: Number(line.product_id), quantity: Number(line.quantity), unit_cost: line.unit_cost === '' ? null : Number(line.unit_cost) })) }); setModal(false); setLines([{ product_id: '', quantity: '1', unit_cost: '' }]); load() } catch (e) { setError(apiMessage(e)) } finally { setSaving(false) } }
  const productName = Object.fromEntries(products.map((p) => [p.product_id, p.name])); const supplierName = Object.fromEntries(suppliers.map((s) => [s.supplier_id, s.company_name]))
  return <><PageHeader title="Purchases" description="Stock received from your suppliers." action={canBuy && <Button onClick={() => { setModal(true); setError('') }}>Record purchase</Button>} />{error && <Notice>{error}</Notice>}{loading ? <LoadingState /> : items.length === 0 ? <EmptyState title="No purchases yet" message={canBuy ? 'Record a purchase to increase stock.' : 'Purchases will appear here.'} /> : <div className="table-card"><table><thead><tr><th>Purchase</th><th>Supplier</th><th>Items</th><th>Total</th><th>Status</th></tr></thead><tbody>{items.map((item) => <tr key={item.purchase_id}><td><strong>#{String(item.purchase_id).padStart(4, '0')}</strong><small className="muted">{formatDate(item.purchase_date)}</small></td><td>{supplierName[item.supplier_id] || `Supplier #${item.supplier_id}`}</td><td>{item.items?.map((line) => `${productName[line.product_id] || `#${line.product_id}`} × ${line.quantity}`).join(', ') || '—'}</td><td><strong>{formatCurrency(item.total_amount)}</strong></td><td><span className="status-pill complete">{item.status}</span></td></tr>)}</tbody></table></div>}{modal && <Modal title="Record a purchase" onClose={() => setModal(false)}><form className="modal-form" onSubmit={submit}><Notice>{error}</Notice><Field label="Supplier"><select required value={supplier} onChange={(e) => setSupplier(e.target.value)}><option value="">Choose supplier</option>{suppliers.map((s) => <option key={s.supplier_id} value={s.supplier_id}>{s.company_name}</option>)}</select></Field><Field label="Purchase lines"><LineEditor lines={lines} products={products} purchase setLines={setLines} /></Field><div className="modal-actions"><Button variant="secondary" onClick={() => setModal(false)}>Cancel</Button><Button type="submit" loading={saving}>Save purchase</Button></div></form></Modal>}</>
}

export function SalesPage() {
  const [items, setItems] = useState([]); const [customers, setCustomers] = useState([]); const [products, setProducts] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [modal, setModal] = useState(false); const [customer, setCustomer] = useState(''); const [lines, setLines] = useState([{ product_id: '', quantity: '1' }]); const [saving, setSaving] = useState(false)
  async function load() { try { setLoading(true); const [o, c, p] = await Promise.all([api.get('/orders/'), api.get('/customers/'), api.get('/products/')]); setItems(o.data); setCustomers(c.data); setProducts(p.data) } catch (e) { setError(apiMessage(e)) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  async function submit(e) { e.preventDefault(); setSaving(true); setError(''); try { await api.post('/orders/', { customer_id: customer ? Number(customer) : null, items: lines.map((line) => ({ product_id: Number(line.product_id), quantity: Number(line.quantity) })) }); setModal(false); setLines([{ product_id: '', quantity: '1' }]); load() } catch (e) { setError(apiMessage(e)) } finally { setSaving(false) } }
  const productName = Object.fromEntries(products.map((p) => [p.product_id, p.name])); const customerName = Object.fromEntries(customers.map((c) => [c.customer_id, `${c.first_name} ${c.last_name}`]))
  return <><PageHeader title="Sales" description="Orders processed by your team." action={<Button onClick={() => { setModal(true); setError('') }}>Record sale</Button>} />{error && <Notice>{error}</Notice>}{loading ? <LoadingState /> : items.length === 0 ? <EmptyState title="No sales yet" message="Record your first sale when a customer checks out." /> : <div className="table-card"><table><thead><tr><th>Sale</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th></tr></thead><tbody>{items.map((item) => <tr key={item.order_id}><td><strong>#{String(item.order_id).padStart(4, '0')}</strong><small className="muted">{formatDate(item.order_date)}</small></td><td>{item.customer_id ? customerName[item.customer_id] || `Customer #${item.customer_id}` : 'Walk-in customer'}</td><td>{item.items?.map((line) => `${productName[line.product_id] || `#${line.product_id}`} × ${line.quantity}`).join(', ') || '—'}</td><td><strong>{formatCurrency(item.total_amount)}</strong></td><td><span className="status-pill complete">{item.status}</span></td></tr>)}</tbody></table></div>}{modal && <Modal title="Record a sale" onClose={() => setModal(false)}><form className="modal-form" onSubmit={submit}><Notice>{error}</Notice><Field label="Customer (optional)"><select value={customer} onChange={(e) => setCustomer(e.target.value)}><option value="">Walk-in customer</option>{customers.map((c) => <option key={c.customer_id} value={c.customer_id}>{c.first_name} {c.last_name}</option>)}</select></Field><Field label="Sale lines"><LineEditor lines={lines} products={products} setLines={setLines} /></Field><div className="modal-actions"><Button variant="secondary" onClick={() => setModal(false)}>Cancel</Button><Button type="submit" loading={saving}>Complete sale</Button></div></form></Modal>}</>
}
